plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '3.0.1'
}

group = 'com.slamperboom'
version = '0.1'

mainClassName = 'com.slamperboom.Main'

repositories {
    mavenCentral()
}

javafx {
    version = '17'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = mainClassName
    mainModule = 'ResumeBuilder.main'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

//    try this
    implementation 'io.github.palexdev:materialfx:11.17.0'

    // https://mvnrepository.com/artifact/org.freemarker/freemarker
    implementation 'org.freemarker:freemarker:2.3.31'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.2'

    // https://mvnrepository.com/artifact/org.jsoup/jsoup
    implementation 'org.jsoup:jsoup:1.20.1'

    implementation "com.openhtmltopdf:openhtmltopdf-pdfbox:1.0.10"

    implementation 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
}

jlink {
    addExtraDependencies("javafx")
    options = ['--bind-services', '--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'ResumeBuilder.main'
    }
    jpackage {
        outputDir = 'ResumeBuilderApp'
        installerName = 'ResumeBuilder-setup'
        installerType = 'msi'
        skipInstaller = true
        if (org.gradle.internal.os.OperatingSystem.current().windows) {
            installerOptions += ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        }
    }
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-class': 'com.slamperboom.Main'
    }
}

tasks.register('jarWithDependencies', Jar) {
    manifest {
        attributes 'Main-Class': 'com.slamperboom.Main'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
