enum FrontendActionEnum {
  OPEN_MAIN_SCREEN = 'OPEN_MAIN_SCREEN',
  OPEN_EDIT_SCREEN = 'OPEN_EDIT_SCREEN',
  UPDATE_CURRENT_SCREEN = 'UPDATE_CURRENT_SCREEN',
  SHOW_MESSAGE = 'SHOW_MESSAGE',
  SHOW_ALERT = 'SHOW_ALERT',
  SHOW_CUSTOM_DIALOG = 'SHOW_CUSTOM_DIALOG',
  OPEN_ABOUT = 'OPEN_ABOUT',
  CLOSE = 'CLOSE',
}

export default FrontendActionEnum;
