enum FrontendActionEnum {
  OPEN_MAIN_SCREEN = 'OPEN_MAIN_SCREEN',
  OPEN_EDIT_SCREEN = 'OPEN_EDIT_SCREEN',
  UPDATE_CURRENT_SCREEN = 'UPDATE_CURRENT_SCREEN',
  SHOW_MESSAGE = 'SHOW_MESSAGE',
  SHOW_CONFIRMATION = 'SHOW_CONFIRMATION',
  SHOW_CUSTOM_DIALOG = 'SHOW_CUSTOM_DIALOG',
  OPEN_ABOUT = 'OPEN_ABOUT',
  OPEN_HELP = 'OPEN_HELP',
  SHOW_ONBOARDING = 'SHOW_ONBOARDING',
  LOCALE_DIALOG = 'LOCALE_DIALOG',
  CLOSE = 'CLOSE',
}

export default FrontendActionEnum;
