quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
quarkus.log.file.level=DEBUG
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=5

%dev.quarkus.log.level=DEBUG
%prod.quarkus.log.level=INFO

quarkus.http.cors=true
#quarkus.http.cors.origins=\\/http:\\/\\/(localhost|127\\.0\\.0\\.1)(:\\d+)?/
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,DELETE,OPTIONS