quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
quarkus.log.file.level=DEBUG
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=5

%dev.quarkus.log.level=DEBUG
%prod.quarkus.log.level=INFO

quarkus.http.host=127.0.0.1

quarkus.http.cors=true
quarkus.http.cors.origins=app://bundle
%dev.quarkus.http.cors.origins=app://bundle,http://localhost:1212
quarkus.http.cors.methods=GET,POST,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=false
